
# How to install

- Using conda
    
        conda install numpy
 
        conda update packagename (for upgrade)

- Using pip   
    
        pip install numpy
        
        pip install <package_name> --upgrade (for upgrade)
        
**You can install any python library using these commands by replacing numpy with your necessary library name.**

In [3]:
! pip install numpy --upgrade

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\User\\.pyenv\\pyenv-win-master\\pyenv-win\\versions\\3.8.6\\Lib\\site-packages\\numpy\\~-ibs\\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/69/65/0d47953afa0ad569d12de5f65d964321c208492064c38fe3b0b9744f8d44/numpy-1.24.4-cp38-cp38-win_amd64.whl.metadata
Using cached numpy-1.24.4-cp38-cp38-win_amd64.whl (14.9 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Successfully uninstalled numpy-1.23.5


# Using library


In [4]:
import numpy as np

In [6]:
np.__version__
# 1.23.5

'1.23.5'

# NumPy 

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Also, it is a Linear Algebra Library for Python, the reason it is so important for Machine Learning with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. 

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: 

- Vectors,Arrays,Matrices 
- Number generation
- Array Attributes and Methods
- Selection, Indexing
- NumPy Operations
- Numpy input & output

Let's start.


## Creating NumPy Arrays, Vector, Matrices

Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

In [7]:
my_list = [1, 2, 3] # vector
type(my_list)

list

In [8]:
ar = np.array(my_list)
type(ar)

numpy.ndarray

In [9]:
my_matrix = [[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
ar_mat = np.array(my_matrix)
ar_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(ar_mat)

numpy.ndarray

In [ ]:
type(my_matrix)

# Number generation

There are lots of built-in ways to generate Arrays


- ### arange
Return evenly spaced values within a given interval.

In [12]:
np.arange(0, 11) # low >= , higher <

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- ### linspace
Return evenly/equally spaced numbers over a specified interval.

In [16]:
np.linspace(0, 10, 10) # low >= , higher <=

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
np.linspace(0, 10, 22).shape

(22,)

- ### zeros and ones
Generate arrays of zeros or ones

In [20]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

 ### eye
Creates an identity matrix

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- ### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [33]:
np.random.rand(3, 3)

array([[0.21006917, 0.91090014, 0.20893831],
       [0.95385698, 0.25454709, 0.27024083],
       [0.32911146, 0.45879752, 0.84645207]])

- ### randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [31]:
np.random.randn(3, 5)

array([[ 0.10123823,  0.15138692, -1.13705785, -0.33464583, -0.39091726],
       [-1.1640027 ,  0.79426139, -0.98713003, -0.77268697, -0.90759712],
       [ 1.19009055, -1.09796828, -0.63517837,  0.87920831, -1.08052064]])

- ### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [29]:
np.random.randint(1, 100, (3, 3))

array([[47, 66, 16],
       [ 3, 31, 37],
       [43, 46, 54]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

- ### Reshape
Returns an array containing the same data with a new shape.

In [34]:
dummy_array = np.random.randint(1, 100, (4, 3))
dummy_array

array([[23, 47, 50],
       [60, 17, 51],
       [50, 59, 89],
       [79, 24,  3]])

In [35]:
dummy_array.shape

(4, 3)

In [36]:
reshaped = dummy_array.reshape(3, 4)
reshaped

array([[23, 47, 50, 60],
       [17, 51, 50, 59],
       [89, 79, 24,  3]])

In [38]:
dummy_array.reshape(2, -1)

array([[23, 47, 50, 60, 17, 51],
       [50, 59, 89, 79, 24,  3]])

In [40]:
# in case you dont know row/col size
reshaped.reshape(-1, 4)

array([[23, 47, 50, 60],
       [17, 51, 50, 59],
       [89, 79, 24,  3]])

- ### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [41]:
rand_arr = np.random.randint(0, 50, (4, 3))
rand_arr

array([[31, 30, 20],
       [25, 25, 41],
       [20, 34, 37],
       [46, 18, 49]])

In [49]:
# help(np.random.randint)

In [42]:
rand_arr.max()

49

In [43]:
# 0 = col, 1 = row
rand_arr.max(axis= 0), rand_arr.max(axis= 1)

(array([46, 34, 49]), array([31, 41, 37, 49]))

In [44]:
rand_arr.argmax()

11

In [45]:
# 0 = col, 1 = row
rand_arr.argmax(axis=0) , rand_arr.argmax(axis=1)

(array([3, 2, 3], dtype=int64), array([0, 2, 2, 2], dtype=int64))

In [46]:
rand_arr.min()

18

In [47]:
rand_arr.argmin()

10

- ### dtype

You can also grab the data type of the object in the array:

In [50]:
rand_arr.dtype

dtype('int32')

In [51]:
float_array = np.random.randn(4, 5)
float_array.dtype

dtype('float64')

In [52]:
float_array

array([[ 0.69932607,  1.57600726,  1.58084451, -0.00733856, -0.15213236],
       [ 0.84608124,  0.88706058, -0.12087032, -1.62455327,  0.40317214],
       [ 1.23282998, -1.76391153,  0.22706169,  0.28289928, -1.30131565],
       [ 0.4997093 ,  1.96589588, -0.89053348, -0.23401908, -0.20693606]])

# NumPy Indexing and Selection

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number.

In [53]:
#Creating sample array
arr = np.random.randint(0, 101, (6, 6))
arr

array([[41, 90, 72, 47, 17, 18],
       [22, 16, 75, 33, 27, 35],
       [50, 98, 95, 54,  9, 88],
       [72,  9, 50, 82, 59, 13],
       [45, 22, 40, 38, 19, 67],
       [47, 69, 49, 58, 36,  1]])

In [68]:
#Selecting a value at an index
arr[0][-4:]

17

In [69]:
#values in a range
arr[1:3, 1:4]

array([[16, 75, 33],
       [98, 95, 54]])

In [70]:
### select and create new array
new = arr[1:3, 1:4]
new

array([[16, 75, 33],
       [98, 95, 54]])

In [ ]:
arr

In [71]:
# conditional selecing
arr[(arr>70)]

array([90, 72, 75, 98, 95, 88, 72, 82])

In [72]:
# conditional selecing
arr[(arr>=70) & (arr<80)]

array([72, 75, 72])



# NumPy Operations

Let's see some examples:

In [73]:
arr = np.arange(0,10, 2)
arr

array([0, 2, 4, 6, 8])

In [74]:
arr + arr

array([ 0,  4,  8, 12, 16])

In [75]:
arr * arr

array([ 0,  4, 16, 36, 64])

In [76]:
arr * 3

array([ 0,  6, 12, 18, 24])

In [77]:
arr % 3

array([0, 2, 1, 0, 2], dtype=int32)

In [78]:
arr / 3

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667])

In [79]:
arr - arr

array([0, 0, 0, 0, 0])

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [80]:
#Square Roots
np.sqrt(arr)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712])

In [81]:
# sin
np.sin(arr)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825])

In [82]:
# cos
np.cos(arr)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003])

In [83]:
#  log
np.log(arr[1:])

array([0.69314718, 1.38629436, 1.79175947, 2.07944154])

 # Practice 
 <img src='img/euclidean.png' width='650'>

In [84]:
import numpy as np


def euclidean(x, y):
    '''
    Python code to find Euclidean distance
    '''
    minus = y - x
    sq = minus ** 2
    sum_sq = np.sum(sq)
    result = np.sqrt(sum_sq)
    return result


In [88]:
# point1 = np.array((1, 2, 3))
# point2 = np.array((1, 1, 1))
point1 = np.random.randint(0, 101, (6, 6))
point2 = np.random.randint(0, 101, (6, 6))

print(point1.shape)
euclidean(point1, point2)

(6, 6)


262.21746700019816

In [ ]:
point1

## I/O with NumPy

In [89]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])

print(a)

np.save('outfile.npy', a)

[1 2 3 4 5]


In [90]:
# load the saved array
b = np.load('outfile.npy')
b

array([1, 2, 3, 4, 5])

In [91]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

np.savez('file.npz', first=a, sec=b)

In [92]:
x = np.load('file.npz')
x['sec']

array([5, 4, 3, 2, 1])

In [93]:
x['first']

array([1, 2, 3, 4, 5])

In [94]:
for i in x.keys():
    print(i)

first
sec


 # Self-study

 <img src='img/assignment.png' width='650'>